
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jun 16 22:05:10 CEST 2013
//----------------------------------------------------

package plg.proto;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 35;
  public static final int DISTINTO = 51;
  public static final int CONSTS = 11;
  public static final int TIPOS = 15;
  public static final int MULT = 54;
  public static final int CHAR = 60;
  public static final int CORCCIERRE = 43;
  public static final int CONST = 12;
  public static final int TIPO = 16;
  public static final int PUNTOYCOMA = 36;
  public static final int PCIERRE = 45;
  public static final int INSTRUCTIONS = 17;
  public static final int SUBPROGRAM = 2;
  public static final int VARS = 13;
  public static final int ENTERO = 7;
  public static final int NATURAL = 30;
  public static final int INTEGER = 31;
  public static final int INT = 59;
  public static final int OUT = 19;
  public static final int DESPIZQ = 57;
  public static final int CHARACTER = 34;
  public static final int AND = 63;
  public static final int NOT = 62;
  public static final int MENORIGUAL = 49;
  public static final int IDENTIFICADOR = 4;
  public static final int IGUAL = 38;
  public static final int CARACTER = 6;
  public static final int OR = 64;
  public static final int IN = 18;
  public static final int CALL = 29;
  public static final int DIV = 55;
  public static final int NATURALES = 5;
  public static final int IF = 22;
  public static final int ENDWHILE = 28;
  public static final int MAYORIGUAL = 48;
  public static final int LLAVECIERRE = 41;
  public static final int EOF = 0;
  public static final int BOOLEAN = 33;
  public static final int error = 1;
  public static final int PROGRAM = 10;
  public static final int COMA = 37;
  public static final int MENOS = 53;
  public static final int MENOR = 47;
  public static final int MOD = 56;
  public static final int DESPDER = 58;
  public static final int MAYOR = 46;
  public static final int REAL = 8;
  public static final int PAP = 44;
  public static final int BARRABAJA = 39;
  public static final int ENDIF = 25;
  public static final int ELSE = 24;
  public static final int IGUALIGUAL = 50;
  public static final int WHILE = 26;
  public static final int CORCAP = 42;
  public static final int FLOAT = 32;
  public static final int THEN = 23;
  public static final int SWAP2 = 21;
  public static final int BOOLEANO = 9;
  public static final int SWAP1 = 20;
  public static final int NAT = 61;
  public static final int LLAVEAP = 40;
  public static final int VAR = 14;
  public static final int SUBPROGRAMS = 3;
  public static final int DO = 27;
  public static final int MAS = 52;
}

